version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fraud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: fraud-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      JWT_SECRET: ${JWT_SECRET}
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_SECRET: ${RAZORPAY_SECRET}
      FRAUD_ML_URL: ${FRAUD_ML_URL}
      LOAN_CHECK_URL: ${LOAN_CHECK_URL}
    depends_on:
      db:
        condition: service_healthy

  fraud-ml:
    build: ./fraud-ml
    container_name: fraud-ml
    ports:
      - "8001:8001"
   
    depends_on:
      - backend

  loan-check:
    build: ./loan-check
    container_name: loan-ml
    ports:
      - "8000:8000"
   
    depends_on:
      - backend

  frontend:
    build: ./frontend
    container_name: fraud-frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - backend
      - fraud-ml
      - loan-check

volumes:
  db_data:
